### ISSUE TITLE
How to configure in CMakeLists.txt?

### ISSUE THREAD

**Issue by godsay1983** [moritz-wundke/Boost-for-Android#119]
Is there anybody to give me an example to configure in CMakeLists.txt?

**Comment by aquawicket** [comment]
This is my method of compiling for Windows using CMake. 

```
## This will create a temporary bash script file,
## and execute msys bash against build-andriod.sh on Windows
## Assuming you have Android NDK, mingw32 and msys.
##
## Default locations are,
## Android NDK = C:/android-ndk-r10d
## mingw32 = C:/mingw/mingw32
## msys = C:/mingw/msys
## Boost for Android = C:/Boost-for-Android-master
## 
## Please set your a folders in the script below

GET_FILENAME_COMPONENT(ANDROID_NDK "C:/android-ndk-r10d" ABSOLUTE)

FUNCTION(ANDROID_BASH arg)
	MESSAGE("MSYS BASH-> ${arg}")
	FILE(WRITE C:/temp ${arg})
	EXECUTE_PROCESS(COMMAND cmd /c C:/mingw/msys/bin/bash /c/temp)
ENDFUNCTION()

### COMPILE ###
ANDROID_BASH("#!/bin/bash
cd C:/Boost-for-Android-master
export PATH=/c/mingw/mingw32/bin:$PATH
export PATH=/c/mingw/msys/bin:$PATH
./build-android.sh --boost=1.53.0 ${ANDROID_NDK}")
```

**Comment by godsay1983** [comment]
I mean after building boost, how to configure cmakelists.txt to use boost in an android project?

**Comment by aquawicket** [comment]
There is quite a bit involved here. 
First, You need to create an Android.mk file for compiling your app.
In that file is where you will include the Boost library. 
I've stripped down one of my Android.mk make files to give you and idea on where to start.

**_Short Example_**
_Android.mk_
```
LOCAL_PATH := $(call my-dir)

LOCAL_MODULE := MyApp
SRC_DIR := $(LOCAL_PATH)/src

LOCAL_C_INCLUDES := $(LOCAL_PATH)
LOCAL_C_INCLUDES += $(SRC_DIR)
LOCAL_CFLAGS :=
LOCAL_LDLIBS :=
APP_SRC := $(wildcard $(SRC_DIR)/*.cpp)
APP_SRC += $(wildcard $(SRC_DIR)/*.c)
LOCAL_SRC_FILES := $(APP_SRC:$(LOCAL_PATH)/%=%)

LOCAL_CPPFLAGS := -DANDROID
LIBDIR := $(LOCAL_PATH)/Release/obj/local/armeabi
ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
	LOCAL_ARM_NEON := true
	LIBDIR := $(LOCAL_PATH)/Release/obj/local/armeabi-v7a
endif

LOCAL_LDFLAGS :=

LOCAL_C_INCLUDES += C:/Boost-for-Android-master/build/include/boost-1_53

LOCAL_LDFLAGS += C:/Boost-for-Android-master/build/lib/libboost_filesystem-gcc-mt-1_53.a
LOCAL_LDFLAGS += C:/Boost-for-Android-master/build/lib/libboost_system-gcc-mt-1_53.a

include $(BUILD_SHARED_LIBRARY)
```

_Application.mk_
```
APP_BUILD_SCRIPT := $(call my-dir)/Android.mk

APP_OPTIM := release

APP_PLATFORM  := android-19
APP_STL               := gnustl_static
APP_CPPFLAGS    := -fexceptions -frtti
APP_ABI               := armeabi-v7a
APP_MODULES    := MyApp
```

I would do some reading up on Android.mk files. Once you get a working Android.mk file, you'll
need to create a CMake script to generate that file. As I said, there is quite a bit involved.

**Comment by godsay1983** [comment]
Can you tell me how to write the Cmake sript file? I have tried but failed. I use find_package(), but it can't find boost.

**Comment by godsay1983** [comment]
Here is my CmakeLists.txt.

`# For more information about using CMake with Android Studio, read the
# documentation: https://d.android.com/studio/projects/add-native-code.html

# Sets the minimum version of CMake required to build the native library.

cmake_minimum_required(VERSION 3.4.1)

# Creates and names a library, sets it as either STATIC
# or SHARED, and provides the relative paths to its source code.
# You can define multiple libraries, and CMake builds them for you.
# Gradle automatically packages shared libraries with your APK.
set(distribution_DIR D:/Develop/VagrentDev/boot2docker_dev/Boost-for-Android/build/out/${ANDROID_ABI})

add_library( # Sets the name of the library.
             native-lib

             # Sets the library as a shared library.
             SHARED

             # Provides a relative path to your source file(s).
             src/main/cpp/native-lib.cpp )

# Searches for a specified prebuilt library and stores the path as a
# variable. Because CMake includes system libraries in the search path by
# default, you only need to specify the name of the public NDK library
# you want to add. CMake verifies that the library exists before
# completing its build.

find_library( # Sets the name of the path variable.
              log-lib

              # Specifies the name of the NDK library that
              # you want CMake to locate.
              log )

add_library(lib_boost_date_time SHARED IMPORTED)
set_target_properties(lib_boost_date_time PROPERTIES IMPORTED_LOCATION
    ${distribution_DIR}/lib/libboost_date_time-clang-mt-1_65_1.a)

# Specifies libraries CMake should link to your target library. You
# can link multiple libraries, such as libraries you define in this
# build script, prebuilt third-party libraries, or system libraries.
target_include_directories(native-lib PRIVATE
                           ${distribution_DIR}/include/boost-1_65_1)

target_link_libraries( # Specifies the target library.
                       native-lib
                       lib_boost_date_time
                       # Links the target library to the log library
                       # included in the NDK.
                       ${log-lib} )`

**Comment by aquawicket** [comment]
Excellent godsay1983.    I had been using CMake since the days before Android support. Seems they have added CMake support since Android Studio 2.2.  I may have to go back and redo all of my scripts now. Good work.

**Comment by wustwg** [comment]
> Here is my CmakeLists.txt.
> 
> ```
> # For more information about using CMake with Android Studio, read the
> # documentation: https://d.android.com/studio/projects/add-native-code.html
> 
> # Sets the minimum version of CMake required to build the native library.
> 
> cmake_minimum_required(VERSION 3.4.1)
> 
> # Creates and names a library, sets it as either STATIC
> # or SHARED, and provides the relative paths to its source code.
> # You can define multiple libraries, and CMake builds them for you.
> # Gradle automatically packages shared libraries with your APK.
> set(distribution_DIR D:/Develop/VagrentDev/boot2docker_dev/Boost-for-Android/build/out/${ANDROID_ABI})
> 
> add_library( # Sets the name of the library.
>              native-lib
> 
>              # Sets the library as a shared library.
>              SHARED
> 
>              # Provides a relative path to your source file(s).
>              src/main/cpp/native-lib.cpp )
> 
> # Searches for a specified prebuilt library and stores the path as a
> # variable. Because CMake includes system libraries in the search path by
> # default, you only need to specify the name of the public NDK library
> # you want to add. CMake verifies that the library exists before
> # completing its build.
> 
> find_library( # Sets the name of the path variable.
>               log-lib
> 
>               # Specifies the name of the NDK library that
>               # you want CMake to locate.
>               log )
> 
> add_library(lib_boost_date_time SHARED IMPORTED)
> set_target_properties(lib_boost_date_time PROPERTIES IMPORTED_LOCATION
>     ${distribution_DIR}/lib/libboost_date_time-clang-mt-1_65_1.a)
> 
> # Specifies libraries CMake should link to your target library. You
> # can link multiple libraries, such as libraries you define in this
> # build script, prebuilt third-party libraries, or system libraries.
> target_include_directories(native-lib PRIVATE
>                            ${distribution_DIR}/include/boost-1_65_1)
> 
> target_link_libraries( # Specifies the target library.
>                        native-lib
>                        lib_boost_date_time
>                        # Links the target library to the log library
>                        # included in the NDK.
>                        ${log-lib} )
> ```

Thanks for your reply , but I have two questions:
Why you impoted lib_boost_date_time as SHARED?It's a static library.
target_include_directories not supported IMPORTED library  until CMake 3.11, now android studio offical cmake is 3.10.2,  how do you solve this problem ?

**Comment by wustwg** [comment]
which one should I choose when I use asic lib?I can't find asci library in out dir .
