### ISSUE TITLE
r16b NDK fails for windows

### ISSUE THREAD

**Issue by aquawicket** [moritz-wundke/Boost-for-Android#120]
Building boost version: 1.65.1
ERROR: C:/android-ndk-r16b is not a valid NDK root

**Comment by aquawicket** [comment]
I was able to get a little further, but still no luck..

**2 changes in build-android.sh**
line 185    
`if [ ! -f "$AndroidNDKRoot/ndk-build.cmd" ]; then`
I added .cmd to this line so it could find the NDK ok.

line 287    
`CXXPATH=$AndroidNDKRoot/toolchains/${TOOLCHAIN}/prebuilt/${PlatformOS}/bin/clang++
I changed ${PlatformOS}-x86_64 to ...   windows-x86_64  doesn't exist. 

still more error to do

**Comment by olyaee** [comment]
@aquawicket I faced the same error. How did you solve it?

**Comment by aquawicket** [comment]
Open build-android.sh and change line 189 from
`  if [ ! -f "$AndroidNDKRoot/ndk-build" ]; then`
to
`  if [ ! -f "$AndroidNDKRoot/ndk-build.cmd" ]; then`

Windows cannot find the path without the file extension.

**Comment by olyaee** [comment]
Thank you! this plus some other changes in build-android.sh worked for me

**Comment by aquawicket** [comment]
Did you have this issue?  https://github.com/moritz-wundke/Boost-for-Android/issues/128

**Comment by olyaee** [comment]
Unfortunately, I have not face the same issue. But I faced another one [#129](https://github.com/moritz-wundke/Boost-for-Android/issues/129). 
I tried both 1.66.0 and 1.65.1 with ndk r16b, and still I have errors.

**Comment by M2tM** [comment]
I've submitted a pull request to resolve this issue while maintaining the correct behavior on linux so nobody else needs to stumble across this incorrectly closed issue.
