### ISSUE TITLE
Boost 1.67: Android < 21 builds Error Since pthread_condattr_setclock is Called When Method is Only Avaliable in Android >= 21

### ISSUE THREAD

**Issue by epicstar** [moritz-wundke/Boost-for-Android#132]
Essentially, I'm unable to fully build the Boost 1.67 libraries for armeabi-v7a and x86. This is very easy to reproduce for me.... All I had to do is run the following on the latest master branch with r16b and 15 seconds into the compilation step, it errored:

```bash
./build-android.sh $ANDROID_NDK_ROOT --toolchain=llvm --arch=armeabi-v7a
```

The fix is easy, which is just to change a couple lines in `thread/detail/config.hpp` to not call `pthread_condattr_setclock`. @gjasny has already provided a patch for this specific issue in 1.67 and fixed it in 1.68. Full details here explained here: https://github.com/boostorg/thread/issues/215 

After adding this patch to the code along with the existing code, I was able to compile all libraries on armeabi-v7a and x86 on Android API 19.

I'm going to create a pull request with a new patch file for 1.67 that includes this fix. I'll link the merge request ASAP.

**Comment by pelya** [comment]
Probably fixed, I did not test the patch.
