### ISSUE TITLE
ERROR: Failed to build boost for android for armeabi-v7a!

### ISSUE THREAD

**Issue by tuanictu97** [moritz-wundke/Boost-for-Android#183]
I build boost for android error !
ERROR: Failed to build boost for android for armeabi-v7a!
Version NDK: 20.0.5594570

**Comment by iljcn** [comment]
I also has the problem
ERROR: Failed to build boost for android for arm64-v8a!
ERROR: Failed to build boost for android for armeabi-v7a!
NDK:r19
windows10

**Comment by tuanictu97** [comment]
> I also has the problem
> ERROR: Failed to build boost for android for arm64-v8a!
> ERROR: Failed to build boost for android for armeabi-v7a!
> NDK:r19
> windows10

I using ubuntu 18.04 - ndk 20 build ok
