### ISSUE TITLE
Symbols from boost_log aren't resolved

### ISSUE THREAD

**Issue by o01eg** [moritz-wundke/Boost-for-Android#215]
I'm trying to build library linked to boost_log and boost_log_setup and when I launch application I got error about missing symbol `_ZN5boost3log12v2s_mt_posix7trivial11from_stringIcEEbPKT_jRNS2_14severity_levelE` 

this symbols declared in libboost_log.a with weak attribute so I suppose it could be reason here

**Comment by o01eg** [comment]
I have disable undefined symbols and on link I got:
```
libs/log/src/setup/default_filter_factory.cpp:325: error: undefined reference to 'bool boost::log::v2s_mt_posix::trivial::from_string<char>(char const*, unsigned int, boost::log::v2s_mt_posix::trivial::severity_level&)'
libs/log/src/setup/default_filter_factory.cpp:325: error: undefined reference to 'bool boost::log::v2s_mt_posix::trivial::from_string<char>(char const*, unsigned int, boost::log::v2s_mt_posix::trivial::severity_level&)'
libs/log/src/setup/default_filter_factory.cpp:325: error: undefined reference to 'bool boost::log::v2s_mt_posix::trivial::from_string<char>(char const*, unsigned int, boost::log::v2s_mt_posix::trivial::severity_level&)'
libs/log/src/setup/default_filter_factory.cpp:325: error: undefined reference to 'bool boost::log::v2s_mt_posix::trivial::from_string<char>(char const*, unsigned int, boost::log::v2s_mt_posix::trivial::severity_level&)'
libs/log/src/setup/default_filter_factory.cpp:325: error: undefined reference to 'bool boost::log::v2s_mt_posix::trivial::from_string<wchar_t>(wchar_t const*, unsigned int, boost::log::v2s_mt_posix::trivial::severity_level&)'
libs/log/src/setup/default_filter_factory.cpp:325: error: undefined reference to 'bool boost::log::v2s_mt_posix::trivial::from_string<wchar_t>(wchar_t const*, unsigned int, boost::log::v2s_mt_posix::trivial::severity_level&)'
libs/log/src/setup/default_filter_factory.cpp:325: error: undefined reference to 'bool boost::log::v2s_mt_posix::trivial::from_string<wchar_t>(wchar_t const*, unsigned int, boost::log::v2s_mt_posix::trivial::severity_level&)'
libs/log/src/setup/default_filter_factory.cpp:325: error: undefined reference to 'bool boost::log::v2s_mt_posix::trivial::from_string<wchar_t>(wchar_t const*, unsigned int, boost::log::v2s_mt_posix::trivial::severity_level&)'
./boost/log/trivial.hpp:71: error: undefined reference to 'char const* boost::log::v2s_mt_posix::trivial::to_string<char>(boost::log::v2s_mt_posix::trivial::severity_level)'
./boost/log/utility/formatting_ostream.hpp:921: error: undefined reference to 'std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >& boost::log::v2s_mt_posix::aux::operator<< <char, std::__ndk1::char_traits<char> >(std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >&, boost::log::v2s_mt_posix::aux::id<boost::log::v2s_mt_posix::aux::process> const&)'
./boost/log/trivial.hpp:71: error: undefined reference to 'wchar_t const* boost::log::v2s_mt_posix::trivial::to_string<wchar_t>(boost::log::v2s_mt_posix::trivial::severity_level)'
./boost/log/utility/formatting_ostream.hpp:921: error: undefined reference to 'std::__ndk1::basic_ostream<wchar_t, std::__ndk1::char_traits<wchar_t> >& boost::log::v2s_mt_posix::aux::operator<< <wchar_t, std::__ndk1::char_traits<wchar_t> >(std::__ndk1::basic_ostream<wchar_t, std::__ndk1::char_traits<wchar_t> >&, boost::log::v2s_mt_posix::aux::id<boost::log::v2s_mt_posix::aux::process> const&)'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by o01eg** [comment]
Looks like `log` and `log_setup` have circular dependencies and should be declared that way. `FindBoost.cmake` I used missed that.

**Comment by zhubinsheng** [comment]
#include "boost/locale.hpp"
hello i build boost success but i build project faild 


`In function `utf8ToLocal(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)':
  IRtekFileSDK.cpp:(.text+0x3d4): undefined reference to `boost::locale::util::get_system_locale(bool)'
  IRtekFileSDK.cpp:(.text+0x3dc): undefined reference to `boost::locale::generator::generator()'
  IRtekFileSDK.cpp:(.text+0x3ec): undefined reference to `boost::locale::generator::generate(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) const'

  IRtekFileSDK.cpp:(.text+0x3f4): undefined reference to `boost::locale::generator::~generator()'
  IRtekFileSDK.cpp:(.text+0x3f8): undefined reference to `boost::locale::info::id'
  IRtekFileSDK.cpp:(.text+0x3fc): undefined reference to `boost::locale::info::id'
  IRtekFileSDK.cpp:(.text+0x468): undefined reference to `boost::locale::conv::between(char const*, char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, boost::locale::conv::method_type)'
  IRtekFileSDK.cpp:(.text+0x51c): undefined reference to `boost::locale::generator::~generator()'
  libIRtekFileSDK.a(IRtekFileSDK.cpp.o): In function `localToUtf8(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)':
  IRtekFileSDK.cpp:(.text+0x580): undefined reference to `boost::locale::util::get_system_locale(bool)'
  IRtekFileSDK.cpp:(.text+0x588): undefined reference to `boost::locale::generator::generator()'
  IRtekFileSDK.cpp:(.text+0x598): undefined reference to `boost::locale::generator::generate(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&) const'
  IRtekFileSDK.cpp:(.text+0x5a0): undefined reference to `boost::locale::generator::~generator()'
  IRtekFileSDK.cpp:(.text+0x5a4): undefined reference to `boost::locale::info::id'
  IRtekFileSDK.cpp:(.text+0x5a8): undefined reference to `boost::locale::info::id'
  IRtekFileSDK.cpp:(.text+0x614): undefined reference to `boost::locale::conv::between(char const*, char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, boost::locale::conv::method_type)'
  IRtekFileSDK.cpp:(.text+0x6c8): undefined reference to `boost::locale::generator::~generator()'`
