### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by kaushal98** [moritz-wundke/Boost-for-Android#249]
Hello Team -

Not sure if it's intentional or just an over-sight, but could you guys please add a license to this repo?

Thanks

**Comment by pelya** [comment]
I guess Boost license would be the right choice. I cannot do it from a phone right now.

**Comment by moritz-wundke** [comment]
I know this is long overdue but how about a MIT license?

**Comment by leosan1234** [comment]
@moritz-wundke  I think the MIT License would be fine.　please add a license file.

**Comment by moritz-wundke** [comment]
@pelya any thoughts here?

**Comment by moritz-wundke** [comment]
Added license file

**Comment by kaushal98** [comment]
Thank you @moritz-wundke
