### ISSUE TITLE
Please stop requiring approvals for pull requests

### ISSUE THREAD

**Issue by pelya** [moritz-wundke/Boost-for-Android#255]
I'm the only active maintainer of this repo, and I cannot merge my own commit, because Github requires someone else to review it.
No, I did not leave the army yet. I just bought myself a used laptop for $100, and I have around 30 minutes per day of free time.

**Comment by moritz-wundke** [comment]
Odd, you should have rights to do so.

**Comment by moritz-wundke** [comment]
Could you check if it's all ok by now?

**Comment by pelya** [comment]
It works now, thank you.
